import Head from "next/head";
import { Inter } from "next/font/google";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { PostMessage } from "@/utils/types";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // Create a state with all the posts
  const [allPosts, setAllPosts] = useState<PostMessage[]>([]);
  // let postComponents

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshots) => {
      setAllPosts(
        snapshots.docs.map(
          (doc) => ({ ...doc.data(), id: doc.id } as PostMessage)
        )
      );
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link
              href={{
                pathname: `/${post.id}`,
                query: { post: JSON.stringify(post) },
              }}
            >
              {/* TODO: Add a counter for comments */}
              <button className="text-sm">
                {post.comments?.length || 0} comments
              </button>
            </Link>
          </Message>
        ))}
      </main>
    </>
  );
}
